server:
  port: 8081

spring:
  application:
    name: auth-service
  jackson:
    time-zone: GMT+08:00
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm

keycloak:
  server-url: http://localhost:8080
  realm: myrealm
  client-id: auth-service
  client-secret: LpoEuiuL9MTp3jGoQh33S9zszWrvXDOR
  admin-username: admin
  admin-password: admin

# Distributed Tracing Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,tracing
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0  # Sample 100% of requests for development
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

# Logging configuration with automatic trace/span IDs via MDC
logging:
  level:
    org.example.auth: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
